### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test0@example.com",
    "password": "123456"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test0@example.com",
    "password": "123456"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with an given email
GET http://localhost:3000/auth/?email=test@example.com

### Delete an particular user with a given ID
DELETE http://localhost:3000/auth/434343

### Update an User
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "tes1@example.com"
}

### Get all users in database
GET http://localhost:3000/auth/